services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url_shortener
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_USER: username
      DATABASE_PASSWORD: password
      DATABASE_NAME: postgres
      SECRET_KEY: suuriSalaisuus
    depends_on:
      - db
    ports:
      - "5000:5000"
volumes:
  postgres_data:
