"""Make access_token of user and admin nullable

Revision ID: 3a8aaa5ca8f6
Revises: 8e4660a8bea1
Create Date: 2025-07-17 00:42:35.285174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8aaa5ca8f6'
down_revision = '8e4660a8bea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
